### ISSUE TITLE
Update to asciidoctorj 1.6.0.alpha.5

### ISSUE THREAD

**Issue by gsmet** [asciidoctor/asciidoctor-ant#68]
Hi,

I don't know exactly why but it seems that asciidoctor-ant needs to be recompiled to support the latest asciidoctorj.

Otherwise, I have the following exception while trying to build our project:
```
/data/home/gsmet/git/beanvalidation-spec/build.xml:226: java.lang.NoSuchMethodError: org.asciidoctor.extension.JavaExtensionRegistry.treeprocessor(Ljava/lang/String;)V
	at org.asciidoctor.ant.AsciidoctorAntTask.registerExtensions(AsciidoctorAntTask.java:123)
	at org.asciidoctor.ant.AsciidoctorAntTask.execute(AsciidoctorAntTask.java:79)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
```

**Comment by binout** [comment]
Release 1.6.0.alpha.5 in progress !
